# Redo all files

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"

# A version range to match for said mod loader - for regular FML @Mod it will be the the FML version. This is currently 47.
loaderVersion="${loader_version_range}"

# mod license
license="${mod_license}"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/roberttkahelin8/thingmajigs/issues"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
# The modid of the mod
modId="thingamajigs"

# The version number of the mod
version="${mod_version}"

# A display name for the mod
displayName="${mod_name}"

# A URL to query for updates for this mod https://docs.neoforged.net/docs/misc/updatechecker/
#updateJSONURL="https://github.com/roberttkahelin8/thingmajigs/blob/main/updates/updates.json"

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://www.curseforge.com/minecraft/mc-mods/blueys-thingamajigs"

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="icon.png"

# A text field displayed in the mod UI
credits="Created by CreativeMasterBonin. Some textures made by Greenspelunking. Other ideas and original artwork by blueman."

# A text field displayed in the mod UI
authors="${mod_authors}"

# Display Test controls the display for your mod in the server connection screen
# MATCH_VERSION means that your mod will cause a red X if the versions on client and server differ. This is the default behaviour and should be what you choose if you have server and client elements to your mod.
# IGNORE_SERVER_VERSION means that your mod will not cause a red X if it's present on the server but not on the client. This is what you should use if you're a server only mod.
# IGNORE_ALL_VERSION means that your mod will not cause a red X if it's present on the client or the server. This is a special case and should only be used if your mod has no server component.
# NONE means that no display test is set on your mod. You need to do this yourself, see IExtensionPoint.DisplayTest for more information. You can define any scheme you wish with this value.
# IMPORTANT NOTE: this is NOT an instruction as to which environments (CLIENT or DEDICATED SERVER) your mod loads on. Your mod should load (and maybe do nothing!) whereever it finds itself.
#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)

# The description text for the mod (multi line!)
description='''${mod_description}'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.

[modproperties.thingamajigs]
    thingamajigsisyes = true

[[dependencies.thingamajigs]]
    modId="neoforge" #mandatory
    # The type of the dependency "required", "optional", "incompatible" or "discouraged" (case insensitive).
    type="required" #mandatory
    # Optional field describing why the dependency is required or why it is incompatible
    # reason="..."
    versionRange="${neo_version_range}" #mandatory
    # An ordering relationship for the dependency.
    # BEFORE - This mod is loaded BEFORE the dependency
    # AFTER - This mod is loaded AFTER the dependency
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT, or SERVER
    side="BOTH"


[[dependencies.thingamajigs]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,1.21.1)"
    ordering="NONE"
    side="BOTH"

[[dependencies.thingamajigs]]
    modId="athena"
    type="optional"
    versionRange="[4.0.0,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.thingamajigs]]
    modId="patchouli"
    type="optional"
    versionRange="[1.21-87,)"